# # session 1
# FROM mcr.microsoft.com/devcontainers/base:jammy
# session 2
FROM firedrakeproject/firedrake-vanilla-default:latest

RUN sudo apt update && sudo apt -y upgrade
RUN sudo apt install -y cmake default-jre gfortran python3-venv wget
